<?php

/**
 * @file
 * The block for recommender system.
 */

/**
 * Implements hook_block_info().
 */
function customize_block_info() {
  $blocks['survey'] = array(
    'info' => t('Survey'),
    'cache' => DRUPAL_CACHE_PER_PAGE, //there are a number of caching options for this
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function customize_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'survey':
      $block['subject'] = t('');
      $block['content'] = survey_blocks();
      break;
  }
  return $block;
}

/**
 * Function survey_blocks.
 */
function survey_blocks() {
  return theme('survey');
}

/**
 * Implements hook_theme().
 * Here you are registering your default tpl for the above block
 */
function customize_theme() {
  return array(
    'survey' => array(
      'template' => 'templates/survey'
    ),
  );
}

/**
 * Implements hook_cron().
 * Here you are added computing application and run recommender after that
 */
function customize_cron() {
    // Add 3 recommenders application
    $recommenders = array();
    $recommenders[0] = array
    (
        'title' => 'Fivestar Recommender',
        'description' => 'Run recommender on users browsing history using the item-item algorithm. Only works for "node" (or "Content") entity type.',
        'algorithm' => 'item2item',
        'data structure' => array
        (
            'preference' => array
            (
                'type' => 'table',
                'name' => 'fivestar_rec_vote',
            ),

            'item similarity' => array
            (
                'type' => 'table',
                'name' => 'fivestar_rec_similarity',
            ),

            'prediction' => array
            (
                'type' => 'table',
                'name' => 'fivestar_rec_prediction',
            ),

            'item entity type' => 'node',
        ),

        'cron callback' => 'fivestar_rec_process_vote',
        'upkeep callback' => 'fivestar_rec_purge_vote',
        'form callback' => 'recommender_command_form',
        'command' => 'item2item',
        'application' => 'recommender',
    );

    $recommenders[1] = array
    (
        'title' => 'Browsing History Recommender',
        'description' => 'Run recommender on users browsing history using the item-item algorithm.',
        'algorithm' => 'item2item_boolean',
        'data structure' => array
            (
                'preference' => array
                (
                    'type' => 'table',
                    'name' => 'history_rec_data',
                    'user field' => 'euid',
                    'item field' => 'nid',
                    'score field' => 'score',
                    'score type' => 'boolean',
                    'timestamp field' => 'updated',
                ),

                'item similarity' => array
                (
                    'type' => 'table',
                    'name' => 'history_rec_item_similarity',
                ),

                        'prediction' => array
                (
                    'type' => 'table',
                    'name' => 'history_rec_prediction',
                ),

                'item entity type' => 'node',
            ),

        'options' => array
        (
            'prediction skip invalid uid' => 1,
        ),

        'form elements callback' => 'history_rec_extra_options',
        'cron callback' => 'history_rec_update_data',
        'form callback' => 'recommender_command_form',
        'command' => 'item2item_boolean',
        'application' => 'recommender',
    );

    $recommenders[2] = array
    (
        'title' => 'Ubercart Recommender',
        'description' => 'Generate product recommendations based on users purchasing history. See technical details in README.txt.',
        'algorithm' => 'item2item_boolean',
        'data structure' => array
        (
            'preference' => array
            (
                'type' => 'table',
                'name' => 'uc_rec_purchase',
                'score type' => 'boolean',
                'no views' => '1',
            ),

            'item similarity' => array
            (
                'type' => 'table',
                'name' => 'uc_rec_similarity',
            ),

            'prediction' => array
            (
                'type' => 'table',
                'name' => 'uc_rec_prediction',
            ),

            'item entity type' => 'node',
        ),

        'cron callback' => 'uc_rec_cron_callback',
        'upkeep callback' => 'uc_rec_upkeep_callback',
        'form callback' => 'recommender_command_form',
        'command' => 'item2item_boolean',
        'application' => 'recommender',
    );

    foreach($recommenders as $data) {
        $default_options = isset($data['options']) ? $data['options'] : array();
        $input = array(
            'algorithm' => $data['algorithm'],
            'data structure' => recommender_prepare_data_structure($data['data structure']),
            'options' => $default_options + (isset($form_state['values']['options']) ? $form_state['values']['options']: array()),
        );

        if (variable_get('recommender_show_database_option', FALSE) && !empty($form_state['values']['common']['database'])) {
            global $databases;
            list($db_name, $db_target) = explode('-', $form_state['values']['common']['database']);
            $input['database'] = $databases[$db_name][$db_target];
        }

        $command = isset($data['command']) ? $data['command'] : $data['algorithm'];
        $result = computing_create($data['application'], $command, $data['title'], $input);

        if ($result) {
            drupal_set_message(t('Adding new recommender command successfully. Please run "drush recommender-run" or use Java agent program to execute the command.'));
        }
        else {
            drupal_set_message(t('Cannot add new recommender command. Please inform site administrators.'), 'error');
        }
    }

    // Delay 1 minute before run recommender
    sleep(60);

    // Run recommender
    $count = 0;
    while ($record = computing_claim('recommender')) {
        drupal_set_message("Processing recommender computation: {$record->id}", 'status');
        recommender_process_record($record);
        computing_update($record);
        $count++;
    };
    drupal_set_message("Processed $count recommender tasks.", "status");
}
